---------------------------------------------------------
-- Name:     AlertsInitialData.sql
-- Purpose : This script populates the OLTP initial data related to alerts. 
-- Steps to execute the script from command line:
-- C:> sqlcmd -S IPAddress\InstanceName -d OLTPDataBaseName -U OLTPUser -P OLTPPassword -v oltpdb="OLTPDataBaseName" -i AlertsInitialData.sql
-- For Example
-- C:> sqlcmd -S PS4714\CLAIRMAILDB -d clairdb -U testoltpuser -P testoltppass -v oltpdb="clairdb" -i AlertsInitialData.sql
----------------------------------------------------------

use $(oltpdb)
go

declare @isExecuted int
declare @scriptversion varchar(30)

begin
        set @scriptversion='5.1.7'
    select  @isExecuted=count(*) from script_audit where scriptname='AlertsInitialData.sql' and scriptversion=@scriptversion;
    if (@isExecuted=1)
        begin
                print 'The AlertsInitialData.sql file is already executed once.Please contact your ClairMail System Administrator'
        end
    else
        begin
                insert into script_audit
                select current_timestamp,
                        null,
                        'AlertsInitialData.sql',
                        @scriptversion,
                        system_user,
                        current_user,
                        hostname.*,
                        null,
                        is_srvrolemember ('sysadmin'),
                        'OLTP Alert Initial Data population script',
                        'STARTED'
                from (select host_name from sys.dm_exec_sessions where status = 'running') as hostname;

                begin transaction

                -- INSERTING into ALERTTYPE
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ('9CD1B747EEF24574AC0A1C3F29D35621', 0, current_timestamp, current_timestamp, '402882311c77845f011c7784b3b30002', 'Low Balance', 'lowBal.message.template', 'lowBal.from', 'lowBal.subject', 'lowBal.rule.template', 'namespace.key.alertSrc', 'lowBal.email.template', 'lowBal.text.email.template', 'lowBal.validation.template');
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ('BA8DB8A7D4F64A65A63E87F7E58F1542', 0, current_timestamp, current_timestamp, '402882311c77845f011c7784b3b30002', 'Statement Available', 'statementAvailable.message.template', 'statementAvailable.from', 'statementAvailable.subject', 'statementAvailable.rule.template', 'namespace.key.alertSrc', 'statementAvailable.email.template', 'statementAvailable.text.email.template', null);
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ('48E7B58234164832ABC68FA5F0CD43A9', 0, current_timestamp, current_timestamp, '402882311c77845f011c7784b3b30002', 'Withdrawal Threshold Exceeded', 'withdrawalThresholdExceeded.message.template', 'withdrawalThresholdExceeded.from', 'withdrawalThresholdExceeded.subject', 'withdrawalThresholdExceeded.rule.template', 'namespace.key.alertSrc', 'withdrawalThresholdExceeded.email.template', 'withdrawalThresholdExceeded.text.email.template', 'withdrawalThresholdExceeded.validation.template');
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ('0E1D223EE1D54157958E2BE0E8A916C4', 0, current_timestamp, current_timestamp, '402882311c77845f011c7784b3b30002', 'Deposit Confirmation', 'depositConfirmation.message.template', 'depositConfirmation.from', 'depositConfirmation.subject', 'depositConfirmation.rule.template', 'namespace.key.alertSrc', 'depositConfirmation.email.template', 'depositConfirmation.text.email.template', null);
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ('F5FB6A58A398487887E1A6823A3DD071', 0, current_timestamp, current_timestamp, '402882311c77845f011c7784b3b30002', 'Overdraft Posted', 'overdraftPosted.message.template', 'overdraftPosted.from', 'overdraftPosted.subject', 'overdraftPosted.rule.template', 'namespace.key.alertSrc', 'overdraftPosted.email.template', 'overdraftPosted.text.email.template', null);
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ('8D6D96F6165541EC9D0E3027F4413A63', 0, current_timestamp, current_timestamp, '402882311c77845f011c7784b3b30002', 'Check Cleared', 'checkCleared.message.template', 'checkCleared.from', 'checkCleared.subject', 'checkCleared.rule.template', 'namespace.key.alertSrc', 'checkCleared.email.template', 'checkCleared.text.email.template', null);
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ('5D5762A86A6F4E69B8C11EE5050F0E71', 0, current_timestamp, current_timestamp, '402882311c77845f011c7784b3b30002', 'Withdrawal Confirmation', 'withdrawalConfirmation.message.template', 'withdrawalConfirmation.from', 'withdrawalConfirmation.subject', 'withdrawalConfirmation.rule.template', 'namespace.key.alertSrc', 'withdrawalConfirmation.email.template', 'withdrawalConfirmation.text.email.template', null);
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ('5D5762A86A6F4E69B8C11EE5050G0H72', 0, current_timestamp, current_timestamp, '402882311c77845f011c7784b3b30002', 'Send Notification', 'lockBox.message.template', 'lockBox.from', 'lockBox.subject', 'lockBox.rule.template', 'namespace.key.conv', 'lockBox.email.template', 'lockBox.text.email.template', null);
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ('5D5762A86A6F4E69B8C11EE5050F0E72', 0, current_timestamp, current_timestamp, '402882311c77845f011c7784b3b30002', 'Transaction Verification', 'transactionVerification.message.template', 'transactionVerification.from', 'transactionVerification.subject', 'transactionVerification.rule.template', 'namespace.key.conv', 'transactionVerification.email.template', 'transactionVerification.text.email.template', null);
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ('402882431e23a835011e23a875170017', 0, current_timestamp, current_timestamp, '402882311c77845f011c7784b3b30002', 'Send Lockbox Notification', 'lockBoxImplNotice.message.template', 'lockBoxImplNotice.from', 'lockBoxImplNotice.subject', 'lockBoxImplNotice.rule.template', 'namespace.key.conv', 'lockBoxImplNotice.email.template', 'lockBoxImplNotice.text.email.template', null);
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ('402882431e23a835011e23a875170018', 0, current_timestamp, current_timestamp, '402882311c77845f011c7784b3b30002', 'Send Lockbox Response', 'lockBoxImplResponse.message.template', 'lockBoxImplResponse.from', 'lockBoxImplResponse.subject', 'lockBoxImplResponse.rule.template', 'namespace.key.conv', 'lockBoxImplResponse.email.template', 'lockBoxImplResponse.text.email.template', null);
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ('4028827a213103ab0121310434aa008c', 0, current_timestamp,current_timestamp,'402882311c77845f011c7784b3b30002', 'Overdraft Protection', 'overdraftProtection.message.template', 'overdraftProtection.from', 'overdraftProtection.subject', 'overdraftProtection.rule.template', 'namespace.key.conv', 'overdraftProtection.email.template' , 'overdraftProtection.text.email.template', null); 
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ('9CD1B747EEF24574AC0A1C3F29D35629', 0, current_timestamp, current_timestamp, '402882311c77845f011c7784b3b30002', 'Username Changed', 'usernameChanged.message.template', 'usernameChanged.from', 'usernameChanged.subject', 'usernameChanged.rule.template', 'namespace.key.alertSrc', 'usernameChanged.email.template', 'usernameChanged.text.email.template', null);
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ('9CD1B747EEF24574AC0A1C3F29D35630', 0, current_timestamp, current_timestamp, '402882311c77845f011c7784b3b30002', 'Password Changed', 'passwordChanged.message.template', 'passwordChanged.from', 'passwordChanged.subject', 'passwordChanged.rule.template', 'namespace.key.alertSrc', 'passwordChanged.email.template', 'passwordChanged.text.email.template', null);
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ('9CD1B747EEF24574AC0A1C3F29D35631', 0, current_timestamp, current_timestamp, '402882311c77845f011c7784b3b30002', 'Account Locked', 'accountLocked.message.template', 'accountLocked.from', 'accountLocked.subject', 'accountLocked.rule.template', 'namespace.key.alertSrc', 'accountLocked.email.template', 'accountLocked.text.email.template', null);
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ('9CD1B747EEF24574AC0A1C3F29D35632', 0, current_timestamp, current_timestamp, '402882311c77845f011c7784b3b30002', 'Account Unlocked', 'accountUnlocked.message.template', 'accountUnlocked.from', 'accountUnlocked.subject', 'accountUnlocked.rule.template', 'namespace.key.alertSrc', 'accountUnlocked.email.template', 'accountUnlocked.text.email.template', null);
                ----To insert Fraud Alerts Attributes in 'alerttype' tables 
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ('4028821419962c370119962c6ed30033', 0, current_timestamp,current_timestamp, '402882311c77845f011c7784b3b30002', 'Recurring Transfer Setup', 'recurringTransferSetup.message.template','recurringTransferSetup.from', 'recurringTransferSetup.subject', 'recurringTransferSetup.rule.template', 'namespace.key.alertSrc', 'recurringTransferSetup.email.template' , 'recurringTransferSetup.text.email.template', null);                        
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ('4028821419962c370119962c6ed30034', 0, current_timestamp,current_timestamp, '402882311c77845f011c7784b3b30002', 'Contact Information Changed', 'contactInformationChanged.message.template','contactInformationChanged.from', 'contactInformationChanged.subject', 'contactInformationChanged.rule.template', 'namespace.key.alertSrc', 'contactInformationChanged.email.template' , 'contactInformationChanged.text.email.template', null);                        
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ( '4028821419962c370119962c6ed30035',0,	current_timestamp, current_timestamp,'402882311c77845f011c7784b3b30002','New Payee Added','newPayeeAdded.message.template','newPayeeAdded.from','newPayeeAdded.subject','newPayeeAdded.rule.template','namespace.key.alertSrc',	'newPayeeAdded.email.template',	'newPayeeAdded.text.email.template', null);
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ( '4028821419962c370119962c6ee20020',0,	current_timestamp, current_timestamp,'402882311c77845f011c7784b3b30002','Payment Threshold Exceeded','paymentThresholdExceeded.message.template','paymentThresholdExceeded.from','paymentThresholdExceeded.subject','paymentThresholdExceeded.rule.template','namespace.key.alertSrc',	'paymentThresholdExceeded.email.template', 'paymentThresholdExceeded.text.email.template', 'paymentThresholdExceeded.validation.template');
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ( '4028821419962c370119962c6ee20021',0,	current_timestamp, current_timestamp,'402882311c77845f011c7784b3b30002','Card Not Present','cardNotPresent.message.template','cardNotPresent.from','cardNotPresent.subject','cardNotPresent.rule.template','namespace.key.conv','cardNotPresent.email.template','cardNotPresent.text.email.template', null);
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ( '4028821419962c370119962c6ee20022',0,	current_timestamp, current_timestamp,'402882311c77845f011c7784b3b30002','Declined Transaction','declinedTransaction.message.template','declinedTransaction.from','declinedTransaction.subject','declinedTransaction.rule.template','namespace.key.conv','declinedTransaction.email.template','declinedTransaction.text.email.template', null);
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ( '4028821419962c370119962c6ee20023',0,	current_timestamp, current_timestamp,'402882311c77845f011c7784b3b30002','Pay At The Pump','payAtThePump.message.template','payAtThePump.from','payAtThePump.subject','payAtThePump.rule.template','namespace.key.conv','payAtThePump.email.template','payAtThePump.text.email.template', null);
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ( '4028821419962c370119962c6ee20024',0,	current_timestamp, current_timestamp,'402882311c77845f011c7784b3b30002','Foreign Country Transaction','foreignCountryTransaction.message.template','foreignCountryTransaction.from','foreignCountryTransaction.subject','foreignCountryTransaction.rule.template','namespace.key.conv','foreignCountryTransaction.email.template','foreignCountryTransaction.text.email.template', null);
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ( '4028821419962c370119962c6ee20025',0,	current_timestamp, current_timestamp,'402882311c77845f011c7784b3b30002','ATM Threshold Exceeded','exceededThresholdAtAtm.message.template','exceededThresholdAtAtm.from','exceededThresholdAtAtm.subject','exceededThresholdAtAtm.rule.template','namespace.key.conv','exceededThresholdAtAtm.email.template','exceededThresholdAtAtm.text.email.template', 'exceededThresholdAtAtm.validation.template');
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ( '4028821419962c370119962c6ee20026',0,	current_timestamp, current_timestamp,'402882311c77845f011c7784b3b30002','Withdrawal Threshold Exceeded Actionable','withdrawalThresholdExceededActionable.message.template','withdrawalThresholdExceededActionable.from','withdrawalThresholdExceededActionable.subject','withdrawalThresholdExceededActionable.rule.template','namespace.key.conv','withdrawalThresholdExceededActionable.email.template','withdrawalThresholdExceededActionable.text.email.template', 'withdrawalThresholdExceededActionable.validation.template');
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ( '4028821419962c370119962c6ee20027',0,	current_timestamp, current_timestamp,'402882311c77845f011c7784b3b30002','Transaction Notification FI Defined Level 1','transactionVerificationFI1.message.template','transactionVerificationFI1.from','transactionVerificationFI1.subject','transactionVerificationFI1.rule.template','namespace.key.conv','transactionVerificationFI1.email.template','transactionVerificationFI1.text.email.template', null);
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ( '4028821419962c370119962c6ee20028',0,	current_timestamp, current_timestamp,'402882311c77845f011c7784b3b30002','Transaction Notification User Defined Level 1','transactionVerificationUserLevel1.message.template','transactionVerificationUserLevel1.from','transactionVerificationUserLevel1.subject','transactionVerificationUserLevel1.rule.template','namespace.key.conv','transactionVerificationUserLevel1.email.template','transactionVerificationUserLevel1.text.email.template', 'transactionVerificationUserLevel1.validation.template');
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ( '4028821419962c370119962c6ee20029',0,	current_timestamp, current_timestamp,'402882311c77845f011c7784b3b30002','Transaction Notification FI Defined Level 2','transactionVerificationFI2.message.template','transactionVerificationFI2.from','transactionVerificationFI2.subject','transactionVerificationFI2.rule.template','namespace.key.conv','transactionVerificationFI2.email.template','transactionVerificationFI2.text.email.template', null);
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ( '4028821419962c370119962c6ee20030',0,	current_timestamp, current_timestamp,'402882311c77845f011c7784b3b30002','Transaction Notification FI Defined Level 3','transactionVerificationFI3.message.template','transactionVerificationFI3.from','transactionVerificationFI3.subject','transactionVerificationFI3.rule.template','namespace.key.conv','transactionVerificationFI3.email.template','transactionVerificationFI3.text.email.template', null);
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ( '4028821419962c370119962c6ee20031',0,	current_timestamp, current_timestamp,'402882311c77845f011c7784b3b30002','Transaction Notification User Defined Level 2','transactionVerificationUserLevel2.message.template','transactionVerificationUserLevel2.from','transactionVerificationUserLevel2.subject','transactionVerificationUserLevel2.rule.template','namespace.key.conv','transactionVerificationUserLevel2.email.template','transactionVerificationUserLevel2.text.email.template', 'transactionVerificationUserLevel2.validation.template');
                Insert into ALERTTYPE (ALERT_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION, MESSAGETEMPLATEKEY, FROMKEY, SUBJECTKEY, RULETEMPLATEKEY, NAMESPACEKEY, EMAILTEMPLATEKEY, TEXTEMAILTEMPLATEKEY, validationtemplatekey) values ( '4028821419962c370119962c6ee20032',0,	current_timestamp, current_timestamp,'402882311c77845f011c7784b3b30002','Transaction Notification User Defined Level 3','transactionVerificationUserLevel3.message.template','transactionVerificationUserLevel3.from','transactionVerificationUserLevel3.subject','transactionVerificationUserLevel3.rule.template','namespace.key.conv','transactionVerificationUserLevel3.email.template','transactionVerificationUserLevel3.text.email.template', 'transactionVerificationUserLevel3.validation.template');
                   

                --- INSERTING into ALERTREFERENCETYPE
                Insert into ALERTREFERENCETYPE (ALERT_REFERENCE_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION) values ('3AE9E4F8E62C4CCB8536310305FE78E5' , 0, current_timestamp, current_timestamp, '402882311c77845f011c7784b3b30002', 'account');
                Insert into ALERTREFERENCETYPE (ALERT_REFERENCE_TYPE_ID, VERSION, LASTUPDATED, CREATEDATE, TENANT_ID, DESCRIPTION) values ('1A9C1621C1B04F5C87BF78072B531EA3' , 0, current_timestamp, current_timestamp, '402882311c77845f011c7784b3b30002', 'user');

                commit;
                update 
                        script_audit 
                set
                    lastupdated=current_timestamp, status='FINISHED'
                where
                    scriptname='AlertsInitialData.sql' 
                and scriptversion= @scriptversion 
                and createdate = (select max(createdate) from script_audit where scriptname='AlertsInitialData.sql' and scriptversion=@scriptversion);
        end
end
Go