---
# Deploy banking_rest_api base + solution package

- name: "checking {{ monitise_root }}/tomcat/webapps/banking_rest_api exist or not"
  stat: path={{ monitise_root }}/tomcat/webapps/banking_rest_api
  register: check_path_rest1
  when: backup_option

- name: "{{ monitise_root }}/tomcat/webapps/banking_rest_api status"
  debug: msg="Skipping the banking_rest_api backup"
  when:  backup_option and check_path_rest1.stat.exists==false

- name: backup old banking_rest_api install
  shell: zip -r  {{ backup_applications }}/banking_rest_api-backup{{ ansible_date_time['date'] + '_' + ansible_date_time['time'].replace(':', '_') }}.zip {{ monitise_root }}/tomcat/webapps/banking_rest_api*
        chdir={{ monitise_root }}/tomcat/webapps
  when: backup_option and check_path_rest1.stat.exists


- name: "create {{ script_temp_dir }}"
  file: path={{ script_temp_dir }} state=directory mode=755

- name: "create {{ script_temp_dir }} directories"
  file: path={{ script_temp_dir }}/{{ item }} state=directory mode=755
  with_items:
  - banking_rest_api
  - banking_rest_api-solution

- name: extract banking_rest_api.war file 
  shell: unzip -o {{ backup_root }}/COREBuilds/{{ core_branch }}/{{ core_build }}/WebUI//{{ banking_rest_api_base_package }}
         chdir={{ script_temp_dir }}/banking_rest_api

- name: checking banking_rest_api solution package exist or not
  stat: path={{ backup_root }}/PSBuilds/{{ psbuild_number }}/{{ banking_rest_api_solution_package }}
  register: check_path_rest2
  when: deploy_solution

- name: banking_rest_api solution package status
  debug: msg="banking_rest_api solution package not found"
  when:  deploy_solution and  check_path_rest2.stat.exists==false

- name: unzip the solution package
  shell: unzip -o {{ backup_root }}/PSBuilds/{{ psbuild_number }}/{{ banking_rest_api_solution_package }} 
         chdir={{ script_temp_dir }}/banking_rest_api-solution
  when: deploy_solution and check_path_rest2.stat.exists

- name: overlay banking_rest_api solution package
  shell: /bin/cp -pbr --suffix=.bkp {{ script_temp_dir }}/banking_rest_api-solution/banking_rest_api/* {{ script_temp_dir }}/banking_rest_api/
  when: deploy_solution and check_path_rest2.stat.exists

- name: generate connection.properites file 
  template: src=connection.properties.j2 dest={{ script_temp_dir }}/banking_rest_api/WEB-INF/classes/connection.properties backup=yes

- name: copy logback.xml
  copy: src=logback.xml dest={{ script_temp_dir }}/banking_rest_api/WEB-INF/classes backup=yes

- name: copy logging.properties
  copy: src=logging.properties dest={{ script_temp_dir }}/banking_rest_api/WEB-INF/classes backup=yes

- name: create new banking_rest_api war file 
  shell: zip -r ../banking_rest_api.war  META-INF/MANIFEST.MF *
         chdir={{ script_temp_dir }}/banking_rest_api

- name: delete tomcat work directory
  shell: rm -rf {{ monitise_root }}/tomcat/work/Catalina/localhost/banking_rest_api {{ monitise_root }}/tomcat/webapps/banking_rest_api {{ monitise_root }}/tomcat/webapps/banking_rest_api.war 

- name: deploy new banking_rest_api 
  shell: cp {{ script_temp_dir }}/banking_rest_api.war {{ monitise_root }}/tomcat/webapps

- name: remove temp banking_rest_api directory
  shell: rm -rf {{ script_temp_dir }}/banking_rest_api*  
