# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
alias ll='ls -hl'
alias lla='ls -al'
alias llt='ls -hlstr' # sorted by time
alias lls='ls -hlsSr' # sorted by size

PS1='\[\033[01;32m\]\u\[\033[01;34m\]@\[\033[01;33m\]\h\[\033[00m\]:\[\033[01;36m\]\w\[\033[00m\]\$ '
export EDITOR=vim
